# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=264

pr:
  branches:
    include:
    - main
    - release/*

trigger: none

resources:
  repositories:
  - repository: source
    type: github
    name: dotnet/workload-versions
    ref: refs/heads/main
    # https://dev.azure.com/dnceng-public/public/_settings/adminservices?resourceId=690f39b4-7746-42c2-be89-281bd7c78b9e
    endpoint: public

variables:
- template: /eng/pipelines/templates/variables/workload-public.yml@self
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml@source

stages:
- template: /eng/pipelines/templates/stages/workload-public-build.yml@self
  parameters:
    sourceBranch: source
    engBranch: self