stages:
- stage: Build
  displayName: Build
  jobs:
  - template: /eng/common/templates/job/job.yml@self
    parameters:
      name: buildRepo
      displayName: Build Repo
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals windows.vs2022.amd64.open
      artifacts:
        publish:
          logs: true
      steps:
      # For checkout mechanics, see:
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
      - checkout: eng
        path: eng
        # path: s
      - checkout: self
        path: self
        # path: s
        workspaceRepo: true
      - powershell: Get-ChildItem -Path "$(Agent.BuildDirectory)\self"
        displayName: List self contents
      - powershell: Copy-Item -Path "$(Agent.BuildDirectory)\eng" -Destination "$(Agent.BuildDirectory)\self" -Exclude '.git','.gitignore' -Recurse -Force
        displayName: Copy eng to self
      - powershell: Get-ChildItem -Path "$(Agent.BuildDirectory)\self"
        displayName: List self contents
      - powershell: 'Get-ChildItem env:'
        displayName: List Environment Variables
      - powershell: >-
          eng/common/build.ps1
          -restore -build -pack -ci -msbuildEngine vs
          -configuration $(_BuildConfig)
          /p:DotNetSignType=$(_SignType)
          /p:TeamName=$(_TeamName)
        displayName: 🟣 Build solution